### ISSUE TITLE
Cache seems broken

### ISSUE THREAD

**Issue by Funcan** [berrange/gerrymander#18]
````
duncan@z400-duncan:~/src/gerrymander$ cat ~/.gerrymander
[server]
hostname=review.openstack.org
port=29418
username=duncan-thomas

[cache]
directory=/home/duncan/.gerrymander.cache
longlifetime=300
shortlifetime=10

[organization]
teams = core
...

duncan@z400-duncan:~/src/gerrymander$ gerrymander todo-mine
Traceback (most recent call last):
  File "/usr/local/bin/gerrymander", line 5, in <module>
    pkg_resources.run_script('gerrymander==1.1', 'gerrymander')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/EGG-INFO/scripts/gerrymander", line 22, in <module>
    sys.exit(CommandTool().execute(sys.argv[1:]))
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/commands.py", line 868, in execute
    self._execute(argv)
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/commands.py", line 903, in _execute
    options.func(config, options)
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/commands.py", line 211, in execute
    self.run(config, client, options)
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/commands.py", line 501, in run
    report.display(options.mode)
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/reports.py", line 334, in display
    output = self.generate()
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/reports.py", line 653, in generate
    query.run(querycb)
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/operations.py", line 124, in run
    self.client.run(self.get_args(500, c.sortkey), mycb)
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/client.py", line 154, in run
    self._purge_cache()
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/client.py", line 151, in _purge_cache
    self._purge_cache_locked()
  File "/usr/local/lib/python2.7/dist-packages/gerrymander-1.1-py2.7.egg/gerrymander/client.py", line 133, in _purge_cache_locked
    then = now - self.cachelifetime
TypeError: unsupported operand type(s) for -: 'float' and 'str'



duncan@z400-duncan:~/src/gerrymander$ cat ~/.gerrymander
[server]
hostname=review.openstack.org
port=29418
username=duncan-thomas

[cache]
#directory=/home/duncan/.gerrymander.cache
#longlifetime=300
#shortlifetime=10

[organization]
teams = core
...


duncan@z400-duncan:~/src/gerrymander$ gerrymander todo-mine
Changes To Do List
------------------

+--------+-------------------------------------+----------------+-----------------------------------+----------+----------+---------------
| Status | URL                                 | Owner          | Subject                           | Created  | Updated  | Approvals     
+--------+-------------------------------------+----------------+-----------------------------------+----------+----------+---------------
| NEW    | https://review.openstack.org/43986  | Dazhao         | Code change for nova support c... | 315 days | 12 days  | v=1,-1,-1     
...

````

**Comment by berrange** [comment]
Fixed in git master in

commit fa59a640c62f09567f2af407e106af9ed90502ae
Author: Daniel P. Berrange <berrange@redhat.com>
Date:   Wed Feb 17 11:21:21 2016 +0000

    Cast cache lifetimes to ints after reading from config
    
    Also fix config parameter name for longlifetime cache
    
    Fixes bug #18
