### ISSUE TITLE
Error running patchreviewstats

### ISSUE THREAD

**Issue by mdbooth** [berrange/gerrymander#24]
$ gerrymander patchreviewstats -p openstack/nova
Traceback (most recent call last):
  File "/usr/bin/gerrymander", line 22, in <module>
    sys.exit(CommandTool().execute(sys.argv[1:]))
  File "/usr/lib/python2.7/site-packages/gerrymander/commands.py", line 1078, in execute
    options.func(config, options)
  File "/usr/lib/python2.7/site-packages/gerrymander/commands.py", line 219, in execute
    self.run(config, client, options)
  File "/usr/lib/python2.7/site-packages/gerrymander/commands.py", line 550, in run
    return super(CommandPatchReviewStats, self).run(config, client, options)
  File "/usr/lib/python2.7/site-packages/gerrymander/commands.py", line 513, in run
    report.display(options.mode)
  File "/usr/lib/python2.7/site-packages/gerrymander/reports.py", line 369, in display
    output.display(mode)
  File "/usr/lib/python2.7/site-packages/gerrymander/reports.py", line 85, in display
    stream.write(self.to_text())
  File "/usr/lib/python2.7/site-packages/gerrymander/reports.py", line 124, in to_text
    blocks.append(report.to_text())
  File "/usr/lib/python2.7/site-packages/gerrymander/reports.py", line 323, in to_text
    data.append(col.get_value(self, row))
  File "/usr/lib/python2.7/site-packages/gerrymander/reports.py", line 59, in get_value
    val = val.encode('utf-8')
AttributeError: 'int' object has no attribute 'encode'

**Comment by berrange** [comment]
This is fixed in git master in 

commit 4f14a12488dc0853c7219ca0f8ee5f2b2d6eed58
Author: Guido Günther <agx@sigxcpu.org>
Date:   Wed May 20 19:07:29 2015 +0200

    reports: Don't fail on int types
    
    The reports can contain integers so don't try to use encode on them:
